GET http://localhost:8081/api/smewallets/orders/findAll

###

POST http://localhost:8081/api/smewallets/orders/create
Content-Type: application/json

{
   "id" : 0,
  "isbnNumber": null,
  "itemName": "test item name",
  "itemDescription":"the item description",
  "billingAddress": " the billing address",
  "saleUnit": "sale unit",
  "quantity": 2,
  "department": "tye department ",
  "conveyanceMethod" : "the conveyance method",
  "deliveryTerms": "the delivery terms",
  "paymentTerms":"the payment terms",
  "placeOfDelivery":"place of delivery",

  "qrCode":"the qr code",


  "orderStatus" : "the order status",
  "raiseInvoice" : "raise invoice",
  "notificationStatus" : "the notification status"

}

###