GET http://localhost:8081/api/smewallets/wallets/findAll
Content-Type: application/json
###

GET https:// 81.199.16.73/api/smewallets/wallets/findAll
Content-Type: application/json

###


GET http://localhost:8081/api/smewallets/wallets/findById/2
Content-Type: application/json

###

#,"emailVerifiedAt":"2019-11-21 10:01:09.626"

POST http://localhost:8081/api/smewallets/wallets/create
Content-Type: application/json

{
  "id" : 0,
  "user" : {"id":1,"email":"samarsanios@gmail.com","emailVerifiedAtStr":"2020-01-08 7:47:25","password":"passs","phoneNumber":"0755","refUserId":103,"name":"Samson Arsanios Samson"},  "name" : "Bank Wallet"

}

###

